import sys
from dotenv import load_dotenv

# Ensure Windows terminal outputs UTF-8 cleanly
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

load_dotenv()

from pathlib import Path
src_path = str(Path(__file__).resolve().parent / "src")
if src_path not in sys.path:
    sys.path.insert(0, src_path)

from interview.service import InterviewSession
from interview.tools import print_interview_state_debug


def main():
    print("=" * 80)
    print(" 🎯 UK CREDIBILITY INTERVIEW: DYNAMIC QUESTION GENERATION & STATE INSPECTOR")
    print("=" * 80)
    print("\n[+] Initializing InterviewSession...")
    print("[+] Dynamically fetching student & university JSON from mock API...")
    print("[+] Running OpenRouter DeepSeek V3: START -> generate_questions -> ask_question...")
    print("[+] Please wait while OpenRouter generates adaptive interview questions...\n")

    session = InterviewSession()
    session.start()

    # Print comprehensive structured debug output
    print_interview_state_debug(session.latest_state)

    print("\n" + "=" * 80)
    print("✅ STATE INSPECTION COMPLETED SUCCESSFULLY!")
    print("   All topics, questions, rubrics, and the initial interviewer utterance")
    print("   have been generated by the LLM and inspected above.")
    print("=" * 80 + "\n")


if __name__ == "__main__":
    main()
