import asyncio
import json
import logging
from dotenv import load_dotenv
from livekit.agents import (
    AutoSubscribe,
    JobContext,
    WorkerOptions,
    cli,
)
from livekit.agents.voice import Agent, AgentSession, events
from livekit.plugins import google, silero

from interview.service import InterviewSession

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("livekit-audio-communicator")


async def entrypoint(ctx: JobContext):
    """
    LiveKit Pure Audio Communicator Entrypoint (LiveKit 1.8.0+):
    - Ear: Silero VAD + Google STT converts candidate voice to text.
    - Brain: InterviewSession (LangGraph) evaluates and formulates the next question.
    - Mouth: Google TTS converts the next question text into audio over WebRTC.
    """
    # 1. Connect to LiveKit Room (Audio Only)
    logger.info(f"Connecting audio communicator to room: {ctx.room.name}")
    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)

    # 2. Wait for candidate to connect their microphone
    logger.info("Waiting for candidate participant to join...")
    participant = await ctx.wait_for_participant()
    logger.info(f"Candidate connected: {participant.identity} ({participant.name})")

    # 3. Initialize the isolated InterviewSession (The Brain)
    interview_session = InterviewSession(session_id=ctx.room.name)

    # 4. Configure Audio Communicator (Ear = Google STT, Mouth = Google TTS)
    agent = Agent(
        instructions="You are an autonomous AI technical interviewer. Ask questions clearly and concisely.",
        vad=silero.VAD.load(),
        stt=google.STT(languages=["en-US"]),
        tts=google.TTS(
            gender="neutral",
            voice_name="en-US-Journey-F",
        ),
    )

    voice_session = AgentSession()

    # 5. Turn-by-Turn Audio Loop:
    # When candidate finishes speaking, Google STT emits final UserInputTranscribedEvent
    @voice_session.on("user_input_transcribed")
    def on_user_input(event: events.UserInputTranscribedEvent):
        if not event.is_final:
            return

        candidate_text = event.transcript.strip()
        if not candidate_text:
            return

        logger.info(f"\n[Candidate Voice Transcribed]: {candidate_text}")

        # The Brain evaluates the answer and formulates the next question or conclusion
        next_text, is_done, eval_data = interview_session.submit_candidate_answer(candidate_text)

        # Broadcast live evaluation metrics over WebRTC Data Channel for frontend UI scorecards
        if eval_data:
            logger.info(
                f"[Evaluation] Score: {eval_data.get('accuracy_score', 0):.1f}% | "
                f"Passed: {eval_data.get('is_passed', False)} | "
                f"Re-ask: {eval_data.get('is_reask', False)}"
            )
            asyncio.create_task(
                ctx.room.local_participant.publish_data(
                    json.dumps(eval_data).encode("utf-8")
                )
            )

        logger.info(f"[Interviewer Response]: {next_text}\n")

        # LiveKit speaks the question generated by the Brain
        asyncio.create_task(voice_session.say(next_text))

    # 6. Start Voice Session & Speak Question 1
    await voice_session.start(agent, room=ctx.room)

    first_question = interview_session.start()
    logger.info(f"Interviewer asks Question 1: {first_question}")
    await asyncio.sleep(1)
    await voice_session.say(first_question)


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint))
