import asyncio
import json
import logging
import os
import sys

# Ensure Windows terminal outputs UTF-8 cleanly
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from dotenv import load_dotenv
from livekit.agents import (
    AutoSubscribe,
    JobContext,
    WorkerOptions,
    cli,
    tts,
)
from livekit.agents.voice import Agent, AgentSession, events
from livekit.plugins import silero
from livekit.plugins.google.beta import GeminiSTT, GeminiTTS

from interview.service import InterviewSession
from interview.tools import print_interview_state_debug

load_dotenv()

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("livekit-audio-communicator")


async def entrypoint(ctx: JobContext):
    """
    LiveKit Pure Audio Communicator Entrypoint:
    - Ear: Silero VAD + Gemini STT converts candidate voice to text.
    - Brain: InterviewSession (LangGraph) evaluates and formulates the next question.
    - Mouth: StreamAdapter + Gemini TTS converts question text into audio over WebRTC.
    """
    # 1. Connect to LiveKit Room (Audio Only)
    logger.info(f"Connecting audio communicator to room: {ctx.room.name}")
    await ctx.connect(auto_subscribe=AutoSubscribe.AUDIO_ONLY)

    # 2. Wait for candidate to connect their microphone
    logger.info("Waiting for candidate participant to join...")
    participant = await ctx.wait_for_participant()
    logger.info(f"Candidate connected: {participant.identity} ({participant.name})")

    # 3. Initialize the isolated InterviewSession (The Brain)
    interview_session = InterviewSession(session_id=ctx.room.name)

    # 4. Configure Audio Communicator (Ear = Gemini STT, Mouth = Gemini TTS via StreamAdapter)
    gemini_tts = GeminiTTS(
        voice_name="Aoede",
        instructions="Speak clearly, warmly, and at a measured pace like a professional UK university interviewer.",
    )
    streaming_tts = tts.StreamAdapter(tts=gemini_tts)

    agent = Agent(
        instructions="You are an autonomous UK university credibility and academic interviewer. Ask questions clearly and concisely.",
        vad=silero.VAD.load(),
        stt=GeminiSTT(language="en-US"),
        tts=streaming_tts,
    )

    voice_session = AgentSession()

    # 5. Turn-by-Turn Audio Loop:
    # When candidate finishes speaking, Gemini STT emits final UserInputTranscribedEvent
    @voice_session.on("user_input_transcribed")
    def on_user_input(event: events.UserInputTranscribedEvent):
        if not event.is_final:
            return

        candidate_text = event.transcript.strip()
        if not candidate_text:
            return

        async def _handle_turn():
            logger.info(f"\n[Candidate Voice Transcribed]: {candidate_text}")

            # The Brain evaluates the answer and formulates the next question or conclusion
            # Run synchronous LangGraph brain execution in thread pool to prevent blocking WebRTC loop
            next_text, is_done, eval_data = await asyncio.to_thread(
                interview_session.submit_candidate_answer, candidate_text
            )

            # Broadcast live evaluation metrics over WebRTC Data Channel for frontend UI scorecards
            if eval_data:
                logger.info(
                    f"[Evaluation] Score: {eval_data.get('accuracy_score', 0):.1f}% | "
                    f"Passed: {eval_data.get('is_passed', False)} | "
                    f"Re-ask: {eval_data.get('is_reask', False)}"
                )
                try:
                    await ctx.room.local_participant.publish_data(
                        json.dumps(eval_data).encode("utf-8")
                    )
                except Exception as e:
                    logger.debug(f"Data channel publish skipped: {e}")

            logger.info(f"[Interviewer Response]: {next_text}\n")

            # LiveKit speaks the question generated by the Brain
            await voice_session.say(next_text)

        asyncio.create_task(_handle_turn())

    # 6. Generate Question 1 & Start Voice Session
    logger.info("Generating Question 1 from student profile & rubric...")
    first_question = await asyncio.to_thread(interview_session.start)

    # Output detailed debug state breakdown to terminal for inspection
    print_interview_state_debug(interview_session.latest_state)

    # Testing Breakpoint: Disconnects live session before audio loop as requested
    # Set BREAKPOINT_AFTER_QUESTION_GEN=false in .env to proceed to full live voice interview
    breakpoint_enabled = os.getenv("BREAKPOINT_AFTER_QUESTION_GEN", "true").lower() in ("true", "1", "yes")
    if breakpoint_enabled:
        print("\n" + "=" * 80)
        print("🛑 [TESTING BREAKPOINT HIT]")
        print("   Question generation, rubrics, and state have been output above.")
        print("   Disconnecting the live voice interview session as requested for debugging.")
        print("   (To continue to the live voice interview, set BREAKPOINT_AFTER_QUESTION_GEN=false in .env)")
        print("=" * 80 + "\n")
        try:
            await ctx.room.disconnect()
        except Exception:
            pass
        return

    await voice_session.start(agent, room=ctx.room)
    logger.info(f"Interviewer asks Question 1: {first_question}")
    await asyncio.sleep(0.5)
    await voice_session.say(first_question)


if __name__ == "__main__":
    cli.run_app(WorkerOptions(entrypoint_fnc=entrypoint))
